export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const RESET_AUTH = 'RESET_AUTH';
export const RESET_USER = 'RESET_USER';
export const SET_TRAINERS = 'SET_TRAINERS';
export const SET_USER = 'SET_USER';
export const GENERIC_USER_FIELD_SET = 'GENERIC_USER_FIELD_SET';
export const SET_USER_TYPE = 'SET_USER_TYPE';
